config/routes.rb
Website::Application.routes.draw do
  resources :contacts

  
  root :to => 'home#index'
  
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :contact_email, :contact_message, :contact_name, :contact_phone, :contact_title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :dump_params
  
  
  
  def dump_params
    Rails.logger.debug "\n\n\n\n\n\n\n\n%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
    Rails.logger.debug "params ==> #{params.inspect}\n\n"
  end
  
  
  
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
require "ultimate_weather_forecasts"

class HomeController < ApplicationController

  include UltimateWeatherForecasts
  
  #def under_construction
  #end
  
  def index
    @weather = whats_the_weather_in("Dallas")
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contact_name %><br />
    <%= f.text_field :contact_name %>
  </div>
  <div class="field">
    <%= f.label :contact_email %><br />
    <%= f.text_field :contact_email %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %><br />
    <%= f.text_field :contact_phone %>
  </div>
  <div class="field">
    <%= f.label :contact_title %><br />
    <%= f.text_field :contact_title %>
  </div>
  <div class="field">
    <%= f.label :contact_message %><br />
    <%= f.text_area :contact_message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <tr>
    <th>Contact name</th>
    <th>Contact email</th>
    <th>Contact phone</th>
    <th>Contact title</th>
    <th>Contact message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.contact_name %></td>
    <td><%= contact.contact_email %></td>
    <td><%= contact.contact_phone %></td>
    <td><%= contact.contact_title %></td>
    <td><%= contact.contact_message %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Contact name:</b>
  <%= @contact.contact_name %>
</p>

<p>
  <b>Contact email:</b>
  <%= @contact.contact_email %>
</p>

<p>
  <b>Contact phone:</b>
  <%= @contact.contact_phone %>
</p>

<p>
  <b>Contact title:</b>
  <%= @contact.contact_title %>
</p>

<p>
  <b>Contact message:</b>
  <%= @contact.contact_message %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/_left_side_nav.html.erb
<h3>Connect</h3>
<h5><a href="http://linkedin.com/in/aghyad" target="_blank">LinkedIn</a></h5>
<h5><a href="http://github.com/aghyad" target="_blank">Github</a></h5>
<h5><a href="http://twitter.com/aghyadsaleh" target="_blank">@AghyadSaleh</a></h5>
<h5><a href="mailto:contact@aghyadsaleh.com">contact@aghyadsaleh.com</a></h5>

<br>
<br>

<a href="mailto:contact@aghyadsaleh.com" title="Pair program with me!">
	<img  src="http://pairprogramwith.me/badge.png" alt="Pair program with me!" />
</a>

app/views/home/index.html.erb
<% content_for :global_alert do %>
  <%= "this Site is currently under construction ... We will be fully available soon".upcase %>
<% end %>


<% content_for :primary do %>
  <div align=center>
    <br><br><br><br>
    <!-- <img src="ruby_image.jpeg" width="150" class="img-polaroid"></img> -->
    <img src="my_business_card.png" class="img-polaroid"></img>

    <br><br><br><br><br><br><br> 

    <% @weather.each do |key, val| %>
      <b><%= key.split("_").join(" ") %></b> : <%= val %> &nbsp; &nbsp; &nbsp; &nbsp;
    <% end %>

  </div>
<% end %>


<% content_for :secondary do %>
  <%= render :partial=>"home/left_side_nav" %>
<% end %>

app/views/home/under_construction.html.erb
<div id="page">
  <div id="sidebar">
	<br><br><br><br>
    <ul id="sidebar-items">
      <li>
        <h3>My LinkedIn Profile:</h3>
        <ul class="links">
          <li><a href="http://linkedin.com/in/aghyad" target="_blank">LinkedIn Account</a></li>
        </ul>
      </li>
    </ul>

	<ul id="sidebar-items">
      <li>
		<br>
        <h3>My Github Account:</h3>
        <ul class="links">
          <li><a href="http://github.com/aghyad" target="_blank">Github Account</a></li>
        </ul>
      </li>
    </ul>
	
	<ul id="sidebar-items">
      <li>
		<br>
        <h3>My Twitter Handle:</h3>
        <ul class="links">
          <li><a href="http://twitter.com/aghyadsaleh" target="_blank">@AghyadSaleh</a></li>
        </ul>
      </li>
    </ul>
	
	<ul id="sidebar-items">
      <li>
		<br><br><br>
        <b>You can also contact me:</b>
		<a href="mailto:aghyad@aghyadsaleh.com">aghyad@aghyadsaleh.com</a>
      </li>
    </ul>
	
  </div>
	<br><br><br><br><br>
  <div align=center id="content">
	<br>
	<h2>
		<!-- Welcome to Aghyad Saleh personal pages and professional <b><a href="http://blog.aghyadsaleh.com">blog</a></b>. -->
		Welcome to Aghyad Saleh personal pages and professional blog.
	</h2>
	<br><img src="ruby_image.jpeg" width="150"></img>&nbsp;&nbsp;&nbsp;&nbsp;<br><br>
	<h3>
		Site is under construction now ... We will be available soon.
	</h3>
	<br><br>
  </div>

  <div id="footer">&nbsp;</div>
</div>

app/views/layouts/_logo.html.erb
<a class="brand" href="/">
	<!-- <span style="font-size:25px;">A</span><span style="font-size:19px;">GHYAD</span><span style="font-size:25px;">S</span><span style="font-size:19px;">ALEH</span><span style="font-size:10px;"> <b>o</b> </span><span style="font-size:18px;">COM</span> -->
	
	<!-- <span style="font-size:25px;">A</span><span style="font-size:19px;">GHYAD</span><span style="font-size:25px;">S</span><span style="font-size:19px;">ALEH</span><span style="font-size:10px;">D<b>O</b>T</span><span style="font-size:18px;">COM</span> -->
	
	<span style="font-size:25px;">A</span><span style="font-size:19px;">GHYAD</span><span style="font-size:25px;">S</span><span style="font-size:19px;">ALEH</span><span style="font-size:10px;"> <b>o</b> </span><span style="font-size:18px;">COM</span>
</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AghyadSaleh.com</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body class="body">
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= render :partial=>"layouts/logo" %>
          <div class="nav-collapse">
            <ul class="nav">
              <li>&nbsp;&nbsp;&nbsp;&nbsp;</li>
              <li class="<%= (params[:action]=="view_resume") ? "active" : "" %>"><%= link_to "My Resume", "/" %></li>
              <li class="<%= (params[:action]=="view_portfolio") ? "active" : "" %>"><%= link_to "My Portfolio", "/" %></li>
              <li class="<%= (params[:action]=="new_contact") ? "active" : "" %>"><%= link_to "Contact Me", "/" %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <% if content_for?(:global_alert) %>
      <br><br>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container" align="center">
            <div align=center  style="width:100%; color:#d00; font-weight:bold; margin-top:12px;">
              <%= yield :global_alert %>
            </div>
          </div>
        </div>
      </div>
      <br>
    <% else %>
      <br><br><br><br>
    <% end %>

    <div class="container">
      <div class="row">
        <div class="span10">
          <%= yield :primary %>
        </div>
        <div class="span2">
          <%= yield :secondary %>
        </div>
      </div>
    </div>
    
    <br><br><br><br>
    <div align="center"><h6>All Rights Reserved &#169; 2010-<%= Time.now.year %></h6></div>
    
  </body>
</html>